---
- name: composer
  src: geerlingguy.composer

- name: zend-framework
  src: https://github.com/thomaslorentsen/ansible-zend-framework.git
  version: origin/master

- name: giffgaff-projects
  src: git+git@github.com:roundpartner/ansible-giffgaff-projects.git
  version: origin/master

- name: giffgaff-servers
  src: git+git@github.com:roundpartner/ansible-giffgaff-servers.git
  version: origin/master

- name: ssh-client
  src: git+git@github.com:thomaslorentsen/ansible-ssh-client.git
  version: origin/master

- name: playlists
  src: git+git@github.com:roundpartner/ansible-playlists.git
  version: origin/master
...