- name: composer
  src: geerlingguy.composer

- name: zend-framework
  src: https://github.com/thomaslorentsen/ansible-zend-framework.git
  version: origin/master

- name: giffgaff-projects
  src: git+git@github.com:roundpartner/ansible-giffgaff-projects.git
  version: origin/master
