---
# run: sudo chown -R $(whoami) /usr/local/share/info

# https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
- name: install coreutils
  homebrew:
    name: coreutils
    state: present

- name: install dev ops tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - maven
    - kubectl
    - kubectx
    - terraform
    - openshift-cli
    - kubernetes-cli
    - ansible

- name: install awscli
  pip:
    name: awscli
...