---
# https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
- name: install coreutils
  homebrew:
    name: coreutils
    state: present

- name: install linux tools
  homebrew:
    name: "{{ item }}"
    state: present
    install_options: "--with-default-names"
  with_items:
    - gnu-sed
    - gnu-tar
...