testing_repos:
  - alpha
  - beta
  - charlie
  - delta
  - echo
  - foxtrot
  - golf
  - hotel
  - india
  - juliett
  - lima
  - kilo
  - mike
  - november
  - oscar
  - papa
  - quebec
  - romeo
  - sierra
  - tango
  - uniform
  - whiskey
  - victor
  - xray
  - yankee
  - zulu
