---
- name: install git
  homebrew:
    name: git
    state: linked
  when: not ansible_check_mode

- name: prompt user to link packages
  debug:
    msg: "now run: sudo brew link {{ item }}"
  with_items:
    - git
  when: not ansible_check_mode

- name: install global git config template
  template:
    src: gitconfig.tpl
    dest: ~/.gitconfig
    
- name: install git message config template
  template:
    src: gitmessage.txt
    dest: ~/.gitmessage.txt

- name: install global git ignore template
  template:
    src: gitignore
    dest: ~/.gitignore_global
...
