---
- name: install git
  homebrew:
    name: git
    state: present

- name: install global git config template
  template:
    src: gitconfig
    dest: ~/.gitconfig
    
- name: install git message config template
  template:
    src: gitmessage.txt
    dest: ~/.gitmessage.txt

- name: install global git ignore template
  template:
    src: gitignore
    dest: ~/.gitignore_global

- name: install gpg
  homebrew:
    name: gpg
    state: present
...
